version: "3"
services:
  wsgi:
    environment: 
      - GUNICORN_CMD_ARGS=-b 0.0.0.0:5000
      - TFSERVING_HOSTNAME=commands_tf_serving:8500
    build:
      context: .
      dockerfile: wsgi.dockerfile
    command: gunicorn --worker-class eventlet -w 1 'service.wsgi:start_production()'
    ports:
      - "5000:5000"
  commands_tf_serving:
    build:
      context: .
      dockerfile: commands.dockerfile
    ports:
      - "8501:8500"
